markdown: kramdown
timezone: Asia/Singapore
google_analytics: UA-97715837-2
disqus-url: marcthe12-github-io.disqus.com
permalink: /blog/:year/:month/:day/:title


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-feed
